(() => {
"use strict";
const C=window.APP_CONFIG;
const API=String(C.apiBaseUrl||"").replace(/\/+$/,"");
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={lang:localStorage.getItem("club_lang")||C.defaultLanguage||"zh",data:null,step:0,photos:[],selected:""};
const T={
zh:{brandSub:"真实活动与认真连接",discover:"发现",apply:"申请",status:"状态",liveNow:"活动持续更新",privacyNote:"只显示活动区域，不公开会员实时位置。",merchant:"商家后台",eyebrow:"LOCAL CONNECTION APP",headline:"附近正在发生",join:"申请加入",mapTitle:"点击闪烁城市查看活动",live:"实时更新",mapNote:"活动区域公开，具体地址仅在确认后开放。",requestSpot:"申请名额",updates:"最新动态",moving:"自动更新",plans:"会员方案",unlock:"解锁更多",humanReview:"人工确认",humanReviewSub:"审核与活动状态清楚",privateDefault:"默认不公开",privateDefaultSub:"资料仅在授权范围内使用",merchantPay:"商家直接收款",merchantPaySub:"付款进入商家自己的账户",application:"会员申请",applicationSub:"一分钟完成，资料默认不公开。",name:"姓名或昵称",age:"年龄",city:"城市",contact:"电话或邮箱",goal:"关系目标",intro:"一句话介绍",offer:"活动或会员方案",photos:"本人照片（最多3张）",consent:"我确认已满18岁，并同意商家仅为审核、活动联系和本人选择的服务使用资料。",back:"上一步",next:"下一步",submit:"提交申请",received:"申请已收到",thanks:"谢谢你的认真填写",saveCode:"请保存申请编号",viewStatus:"查看状态",statusHeading:"查询申请状态",applicationCode:"申请编号",check:"查询",popular:"最受欢迎",month:"月",choose:"选择",platform:"俱乐部发布",activity:"活动更新",goalOptions:[["serious","认真寻找长期关系"],["marriage","希望认识结婚对象"],["friends","先从朋友开始"]],statusLabels:{submitted:"已提交",under_review:"审核中",approved:"已通过",awaiting_payment:"待付款",payment_pending:"付款待确认",payment_received:"已收款",confirmed:"报名成功",venue_unlocked:"地址已开放",checked_in:"已签到",completed:"已完成",rejected:"未通过",cancelled:"已取消"}},
en:{brandSub:"Real events and serious connections",discover:"Discover",apply:"Apply",status:"Status",liveNow:"Activity keeps updating",privacyNote:"Only event areas are shown—never member live locations.",merchant:"Merchant admin",eyebrow:"LOCAL CONNECTION APP",headline:"Happening nearby",join:"Apply",mapTitle:"Tap a pulsing city to view activity",live:"Live updates",mapNote:"Event areas are public; exact venues unlock only after confirmation.",requestSpot:"Request a spot",updates:"Latest updates",moving:"Auto updating",plans:"Membership plans",unlock:"Unlock more",humanReview:"Human review",humanReviewSub:"Clear review and event status",privateDefault:"Private by default",privateDefaultSub:"Information is used only within authorized boundaries",merchantPay:"Merchant-direct payment",merchantPaySub:"Funds go to the merchant's own account",application:"Member application",applicationSub:"Complete in one minute. Private by default.",name:"Name or nickname",age:"Age",city:"City",contact:"Phone or email",goal:"Relationship goal",intro:"One-line introduction",offer:"Event or membership",photos:"Real photos (up to 3)",consent:"I confirm I am 18 or older and consent to use of this information only for review, event contact, and services I choose.",back:"Back",next:"Next",submit:"Submit",received:"Application received",thanks:"Thank you for applying",saveCode:"Save application number",viewStatus:"View status",statusHeading:"Check application status",applicationCode:"Application number",check:"Check",popular:"Most popular",month:"month",choose:"Choose",platform:"Club post",activity:"Event update",goalOptions:[["serious","Seeking a serious long-term relationship"],["marriage","Hoping to meet a future spouse"],["friends","Start as friends"]],statusLabels:{submitted:"Submitted",under_review:"Under review",approved:"Approved",awaiting_payment:"Awaiting payment",payment_pending:"Payment pending",payment_received:"Payment received",confirmed:"Confirmed",venue_unlocked:"Venue unlocked",checked_in:"Checked in",completed:"Completed",rejected:"Rejected",cancelled:"Cancelled"}}
};
const tr=k=>{let v=T[state.lang];for(const p of k.split("."))v=v?.[p];return v??k};
const loc=(o,f)=>state.lang==="zh"?(o?.[f+"_zh"]||o?.[f+"_en"]||""):(o?.[f+"_en"]||o?.[f+"_zh"]||"");
async function request(path,opt={}){const r=await fetch(API+path,opt);let j=null;try{j=await r.json()}catch{}if(!r.ok)throw new Error(j?.error||`Request failed (${r.status})`);return j}
async function load(){if(!API)throw new Error("Backend URL is not configured");state.data=await request("/api/public");render()}
function applyText(){document.documentElement.lang=state.lang==="zh"?"zh-CN":"en";$$("[data-i18n]").forEach(x=>{const v=tr(x.dataset.i18n);if(typeof v==="string")x.textContent=v});$("#langBtn").textContent=state.lang==="zh"?"EN":"中文"}
function render(){applyText();const d=state.data,s=d.settings||{},events=d.events||[],posts=d.posts||[],plans=d.plans||[];$("#brandName").textContent=s.brand_name||"Singles Club";document.title=s.page_title||s.brand_name||"Singles Club";$("#adminLink").href=C.adminUrl||API+"/admin.html";renderMap(events);renderPosts(posts);renderPlans(plans);renderFeatured(events);renderOffer(events,plans);renderGoals();renderSchema(s,events)}
function renderMap(events){const map=$("#map");map.querySelectorAll(".pin").forEach(x=>x.remove());const c=[[28,72],[48,82],[69,34],[75,67],[45,48]];events.slice(0,5).forEach((e,i)=>{const b=document.createElement("button");b.className="pin";b.style.left=c[i][1]+"%";b.style.top=c[i][0]+"%";const spots=Math.max(0,Number(e.capacity||0)-Number(e.confirmed_count||0));b.innerHTML=`<b></b><span><strong>${e.city||""}</strong><br>${loc(e,"title")} · ${spots} spots</span>`;b.onclick=()=>choose(`event:${e.id}`);map.appendChild(b)})}
function renderPosts(posts){const list=posts.length?[...posts,...posts]:[];$("#feedTrack").innerHTML=list.map(p=>`<article class="post"><div class="post-head"><span class="tag ${p.post_type==="activity"?"activity":""}">${p.post_type==="activity"?tr("activity"):tr("platform")}</span><small>${new Date(p.created_at).toLocaleDateString()}</small></div><p>${loc(p,"content")}</p></article>`).join("")}
function renderPlans(plans){$("#pricing").innerHTML=plans.map((p,i)=>`<article class="plan ${i===1?"popular":""}">${i===1?`<span class="popular-badge">${tr("popular")}</span>`:""}<h3>${p.name}</h3><div class="amount">$${Number(p.price).toFixed(0)}<small> / ${tr("month")}</small></div><p>${loc(p,"summary")}</p><button class="${i===1?"primary-btn":"secondary-btn"}" data-plan="${p.id}">${tr("choose")}</button></article>`).join("");$$("[data-plan]").forEach(b=>b.onclick=()=>choose("plan:"+b.dataset.plan))}
function renderFeatured(events){const e=events[0];if(!e){$("#featuredTitle").textContent="—";$("#featuredMeta").textContent="—";return}$("#featuredTitle").textContent=loc(e,"title");$("#featuredMeta").textContent=`${new Date(e.start_at).toLocaleString(state.lang==="zh"?"zh-CN":"en-US",{dateStyle:"medium",timeStyle:"short"})} · ${e.city||""} · $${Number(e.price||0).toFixed(0)}`;$("#featuredBtn").onclick=()=>choose(`event:${e.id}`)}
function renderOffer(events,plans){$("#offerSelect").innerHTML=[...events.map(e=>`<option value="event:${e.id}">${loc(e,"title")} · $${Number(e.price||0).toFixed(0)}</option>`),...plans.map(p=>`<option value="plan:${p.id}">${p.name} · $${Number(p.price).toFixed(0)}</option>`)].join("");if(state.selected)$("#offerSelect").value=state.selected}
function renderGoals(){$("#goalSelect").innerHTML=`<option value="">—</option>`+tr("goalOptions").map(([v,l])=>`<option value="${v}">${l}</option>`).join("")}
function choose(v){state.selected=v;renderOffer(state.data.events||[],state.data.plans||[]);openApply()}
function openApply(){state.step=0;$("#applyForm").reset();state.photos=[];$("#preview").innerHTML="";$("#applyError").textContent="";$("#applyForm").style.display="block";$("#success").classList.remove("show");renderStep();$("#applyDialog").showModal()}
function openStatus(){$("#statusResult").innerHTML="";$("#statusDialog").showModal()}
function renderStep(){$$(".step").forEach((x,i)=>x.classList.toggle("active",i===state.step));$$(".progress i").forEach((x,i)=>x.classList.toggle("active",i<=state.step));$("#backBtn").style.visibility=state.step?"visible":"hidden";$("#nextBtn").textContent=state.step===2?tr("submit"):tr("next")}
function validatePhotos(files){if(files.length>C.maxPhotos)throw new Error(`Maximum ${C.maxPhotos} photos`);files.forEach(f=>{if(!C.allowedPhotoTypes.includes(f.type))throw new Error("Unsupported image type");if(f.size>C.maxPhotoBytes)throw new Error("Image exceeds 5MB")})}
function renderPreview(){$("#preview").innerHTML=state.photos.map((f,i)=>`<div class="preview-item"><img src="${URL.createObjectURL(f)}"><button type="button" data-rm="${i}">×</button></div>`).join("");$$("[data-rm]").forEach(b=>b.onclick=()=>{state.photos.splice(Number(b.dataset.rm),1);renderPreview()})}
async function submitApplication(){const fd=new FormData($("#applyForm"));state.photos.forEach(f=>fd.append("photos",f));const j=await request("/api/applications",{method:"POST",body:fd});$("#applyForm").style.display="none";$("#success").classList.add("show");$("#code").textContent=j.application_code}
function timeline(status){return C.statusOrder.map(s=>`<div class="${C.statusOrder.indexOf(s)<=C.statusOrder.indexOf(status)?"done":""}">● ${tr("statusLabels."+s)}</div>`).join("")}
function renderStatus(j){let payment="";if(["approved","awaiting_payment","payment_pending"].includes(j.status)&&j.payment){if(j.payment.stripe_url)payment+=`<div class="paymentbox"><strong>Stripe</strong><p><a class="primary-btn" target="_blank" rel="noopener" href="${j.payment.stripe_url}">Pay securely</a></p></div>`;if(j.payment.zelle_contact)payment+=`<div class="paymentbox"><strong>Zelle</strong><p>${j.payment.zelle_name||""}<br>${j.payment.zelle_contact}</p></div>`;if(j.payment.has_qr)payment+=`<div class="paymentbox"><strong>${j.payment.qr_label||"Payment QR"}</strong><img class="qr" src="${API}/api/payment-qr"></div>`}return `<div class="statusbox"><h3>${tr("statusLabels."+j.status)}</h3><p>${j.event_title||j.plan_name||""}</p><div class="timeline">${timeline(j.status)}</div>${payment}${j.private_venue?`<div class="paymentbox"><strong>Venue</strong><p>${j.private_venue}</p></div>`:""}</div>`}
function renderSchema(s,events){const g=[{"@type":"Organization","name":s.brand_name||"Singles Club","url":C.siteUrl,"email":s.contact_email||"","areaServed":s.city||""},{"@type":"WebSite","name":s.brand_name||"Singles Club","url":C.siteUrl}];events.forEach(e=>g.push({"@type":"Event","name":e.title_en||e.title_zh,"startDate":e.start_at,"eventAttendanceMode":"https://schema.org/OfflineEventAttendanceMode","eventStatus":"https://schema.org/EventScheduled","location":{"@type":"Place","name":e.public_venue||e.city||"","address":{"@type":"PostalAddress","addressLocality":e.city||"","addressRegion":e.region||"","addressCountry":e.country||"US"}},"offers":{"@type":"Offer","price":String(e.price||0),"priceCurrency":e.currency||"USD","url":C.siteUrl,"availability":"https://schema.org/LimitedAvailability"}}));$("#structuredData").textContent=JSON.stringify({"@context":"https://schema.org","@graph":g})}
$("#langBtn").onclick=()=>{state.lang=state.lang==="zh"?"en":"zh";localStorage.setItem("club_lang",state.lang);render()};
["#openApplySide","#openApplyTop","#openApplyMobile"].forEach(s=>$(s).onclick=openApply);
["#openStatusSide","#openStatusTop","#openStatusMobile"].forEach(s=>$(s).onclick=openStatus);
$("#closeApply").onclick=()=>$("#applyDialog").close();$("#closeStatus").onclick=()=>$("#statusDialog").close();
$("#photos").onchange=e=>{try{validatePhotos([...e.target.files]);state.photos=[...e.target.files];renderPreview();$("#applyError").textContent=""}catch(err){$("#applyError").textContent=err.message;e.target.value=""}};
$("#backBtn").onclick=()=>{if(state.step){state.step--;renderStep()}};
$("#nextBtn").onclick=async()=>{const active=$$(".step")[state.step],bad=[...active.querySelectorAll("input,select,textarea")].find(x=>!x.checkValidity());if(bad)return bad.reportValidity();if(state.step<2){state.step++;return renderStep()}try{$("#nextBtn").disabled=true;await submitApplication()}catch(e){$("#applyError").textContent=e.message}finally{$("#nextBtn").disabled=false}};
$("#statusForm").onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);$("#statusResult").innerHTML="Loading…";try{const j=await request("/api/status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(fd))});$("#statusResult").innerHTML=renderStatus(j)}catch(err){$("#statusResult").innerHTML=`<div class="error">${err.message}</div>`}};
$("#successStatusBtn").onclick=()=>{$("#applyDialog").close();openStatus()};
load().catch(e=>document.body.insertAdjacentHTML("afterbegin",`<div style="padding:12px;text-align:center;background:#fff3cd;color:#6b5200;font-family:sans-serif">后端连接失败：${e.message}</div>`));
})();