
(()=>{"use strict";
const C=window.APP_CONFIG,API=C.apiBaseUrl.replace(/\/+$/,""),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={lang:localStorage.getItem('lang')||C.defaultLanguage,data:null,active:0,timer:null,lastMember:null,lastBooking:null};
const T={zh:{brandSub:"付费会员制活动俱乐部",discover:"发现",join:"成为会员",status:"查询",admin:"商家后台",membersOnly:"仅向有效会员开放",membersOnlySub:"会员费取得俱乐部资格；单次活动费用以活动页面为准。",headline:'先成为会员，再走进<span>每一次真实相遇</span>',headlineSub:"不同会员等级，对应不同规模与参与方式的线下活动。",mapTitle:"会员活动正在发生",live:"持续更新",mapCenter:"选择等级<br>进入活动",mapNote:"只显示公开活动区域，具体地址在确认后开放。",featured:"当前推荐活动",book:"会员报名",updates:"正在发生",plans:"先选择会员资格",memberRule:"会员资格",memberRuleSub:"只有有效会员可以报名每一次活动。",tierRule:"等级权限",tierRuleSub:"高等级包含低等级活动访问资格。",eventFee:"活动费用",eventFeeSub:"会员费与单次活动费分别显示。",memberTitle:"开通会员资格",memberSub:"填写资料并选择会员等级，系统立即生成会员编号和付款方式。",name:"姓名或昵称",age:"年龄",city:"城市",contact:"电话或邮箱",intro:"简单介绍",preferences:"希望参加的活动或交流方式",tier:"会员等级",photo:"本人照片（可选）",consent:"我已满18岁，并同意当前组织方为会员管理和活动联系使用我提交的信息。",createMembership:"生成会员编号",memberCreated:"会员编号已生成",payMethod:"付款方式",payRef:"付款备注（可选）",paid:"我已支付会员费",bookingTitle:"会员活动报名",memberNumber:"会员编号",createBooking:"生成活动报名编号",bookingCreated:"活动报名编号已生成",paidEvent:"我已支付活动费",statusTitle:"查询会员或活动报名",membership:"会员资格",eventBooking:"活动报名",bookingNumber:"活动报名编号",check:"查询",active:"有效会员",statusLabels:{awaiting_payment:"待付款",payment_pending:"付款待确认",active:"有效会员",expired:"已到期",suspended:"已暂停",cancelled:"已取消",refunded:"已退款",payment_received:"已确认收款",confirmed:"名额已确认",venue_unlocked:"地址已开放",checked_in:"已签到",completed:"已完成"}},
en:{brandSub:"Paid-membership activity club",discover:"Discover",join:"Become a member",status:"Status",admin:"Merchant admin",membersOnly:"Active members only",membersOnlySub:"Membership grants club access. Individual event fees are shown separately.",headline:'Become a member, then enter <span>every real-world experience</span>',headlineSub:"Different membership tiers unlock different activity sizes and participation options.",mapTitle:"Member activities are happening",live:"Live updates",mapCenter:"Choose a tier<br>Enter activities",mapNote:"Only public activity areas are shown. Exact venues unlock after confirmation.",featured:"Featured activity",book:"Member booking",updates:"What's happening",plans:"Choose membership first",memberRule:"Membership access",memberRuleSub:"Only active members can book activities.",tierRule:"Tier access",tierRuleSub:"Higher tiers include lower-tier activity access.",eventFee:"Event fees",eventFeeSub:"Membership and event fees are displayed separately.",memberTitle:"Activate membership",memberSub:"Enter your details and choose a tier to receive a member number and payment options.",name:"Name or nickname",age:"Age",city:"City",contact:"Phone or email",intro:"Brief introduction",preferences:"Activities or interaction styles you prefer",tier:"Membership tier",photo:"Real photo (optional)",consent:"I am 18 or older and consent to use of my information for membership administration and activity contact.",createMembership:"Create member number",memberCreated:"Member number created",payMethod:"Payment method",payRef:"Payment reference (optional)",paid:"I paid the membership fee",bookingTitle:"Member event booking",memberNumber:"Member number",createBooking:"Create event booking number",bookingCreated:"Event booking number created",paidEvent:"I paid the event fee",statusTitle:"Check membership or event booking",membership:"Membership",eventBooking:"Event booking",bookingNumber:"Event booking number",check:"Check",active:"Active member",statusLabels:{awaiting_payment:"Awaiting payment",payment_pending:"Payment pending",active:"Active member",expired:"Expired",suspended:"Suspended",cancelled:"Cancelled",refunded:"Refunded",payment_received:"Payment confirmed",confirmed:"Spot confirmed",venue_unlocked:"Venue unlocked",checked_in:"Checked in",completed:"Completed"}}};
const tr=k=>{let v=T[state.lang];for(const p of k.split('.'))v=v?.[p];return v??k};const loc=(o,f)=>state.lang==='zh'?(o?.[f+'_zh']||o?.[f+'_en']||''):(o?.[f+'_en']||o?.[f+'_zh']||'');
async function req(path,opt={}){const r=await fetch(API+path,{...opt,headers:{'Accept':'application/json',...(opt.headers||{})}});let j=null;try{j=await r.json()}catch{}if(!r.ok)throw new Error(j?.error||`Request failed (${r.status})`);return j}
function text(){$$('[data-t]').forEach(x=>x.textContent=tr(x.dataset.t));$$('[data-th]').forEach(x=>x.innerHTML=tr(x.dataset.th));$('#lang').textContent=state.lang==='zh'?'EN':'中文'}
function payment(p,code){if(!p)return'';let h='<div class="payment">';if(p.stripe_url){const u=p.stripe_url+(p.stripe_url.includes('?')?'&':'?')+'client_reference_id='+encodeURIComponent(code);h+=`<a class="primary paylink" target="_blank" rel="noopener" href="${u}">Stripe</a>`}if(p.zelle_contact)h+=`<div class="box"><strong>Zelle</strong><p>${p.zelle_name||''}<br>${p.zelle_contact}</p></div>`;if(p.has_qr)h+=`<div class="box"><strong>${p.qr_label||'QR'}</strong><img class="qr" src="${API}/api/payment-qr"></div>`;return h+'</div>'}
async function load(){state.data=await req('/api/public');render()}
function render(){text();const d=state.data,s=d.settings||{};$('#brand').textContent=s.brand_name||'Singles Club';$('#admin').href=C.adminUrl;$('#tierSelect').innerHTML=d.plans.map(p=>`<option value="${p.tier}">${loc(p,'name')} · $${Number(p.price).toFixed(0)}</option>`).join('');$('#plans').innerHTML=d.plans.map((p,i)=>`<article class="plan ${i===1?'popular':''}"><span class="tier">${p.tier}</span><h3>${loc(p,'name')}</h3><div class="price">$${Number(p.price).toFixed(0)}</div><p>${loc(p,'summary')}</p><button class="${i===1?'primary':'soft'}" data-tier="${p.tier}">${tr('join')}</button></article>`).join('');$$('[data-tier]').forEach(b=>b.onclick=()=>openMember(b.dataset.tier));renderMap();renderFeed();rotate()}
function renderFeed(){const a=state.data.posts.length?[...state.data.posts,...state.data.posts]:[];$('#feed').innerHTML=a.map(p=>`<article class="post"><span class="badge">${p.theme||'club'}</span><h3>${loc(p,'title')||tr('updates')}</h3><p>${loc(p,'content')}</p></article>`).join('')}
function renderMap(){const m=$('#map');m.querySelectorAll('.pin').forEach(x=>x.remove());const c=[[28,72],[48,82],[69,34],[75,67],[45,48]];state.data.events.slice(0,5).forEach((e,i)=>{const b=document.createElement('button');b.className='pin';b.dataset.i=i;b.style.left=c[i][1]+'%';b.style.top=c[i][0]+'%';b.innerHTML=`<b></b><span><strong>${e.city}</strong><br>${loc(e,'title')} · ${e.required_tier}</span>`;b.onclick=()=>openBooking(e);m.appendChild(b)});feature()}
function feature(){const events=state.data.events;if(!events.length)return;state.active%=events.length;$$('.pin').forEach((x,i)=>x.classList.toggle('active',i===state.active));const e=events[state.active];$('#featureTitle').textContent=loc(e,'title');$('#featureMeta').textContent=`${new Date(e.start_at).toLocaleString()} · ${e.required_tier} · $${Number(e.price).toFixed(0)}`;$('#featureBook').onclick=()=>openBooking(e)}
function rotate(){clearInterval(state.timer);state.timer=setInterval(()=>{state.active=(state.active+1)%Math.max(1,state.data.events.length);feature()},C.rotationSeconds*1000)}
function openMember(tier='community'){$('#memberForm').reset();$('#memberSuccess').hidden=true;$('#memberForm').hidden=false;$('#memberError').textContent='';$('#tierSelect').value=tier;$('#memberDialog').showModal()}
function openBooking(e){$('#bookingForm').reset();$('#bookingSuccess').hidden=true;$('#bookingForm').hidden=false;$('#bookingError').textContent='';$('#bookingForm').event_id.value=e.id;$('#bookingEventName').textContent=`${loc(e,'title')} · ${e.required_tier} · $${Number(e.price).toFixed(2)}`;$('#bookingDialog').showModal()}
['#joinSide','#joinTop','#joinMobile'].forEach(s=>$(s).onclick=()=>openMember());['#statusSide','#statusTop','#statusMobile'].forEach(s=>$(s).onclick=()=>$('#statusDialog').showModal());$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#lang').onclick=()=>{state.lang=state.lang==='zh'?'en':'zh';localStorage.setItem('lang',state.lang);render()};
$('#memberForm').onsubmit=async e=>{e.preventDefault();try{const fd=new FormData(e.target),j=await req('/api/memberships',{method:'POST',body:fd});state.lastMember={...j,contact:fd.get('contact')};e.target.hidden=true;$('#memberSuccess').hidden=false;$('#memberNumber').textContent=j.member_number;$('#memberCheckout').innerHTML=`<div class="box"><strong>${j.plan.name_zh}</strong><p>$${Number(j.plan.price).toFixed(2)} · ${j.plan.duration_days} days</p></div>`+payment(j.payment,j.member_number)}catch(x){$('#memberError').innerHTML=`<div class="error">${x.message}</div>`}};
$('#memberPaid').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));try{await req('/api/membership-payment-submitted',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...o,member_number:state.lastMember.member_number,contact:state.lastMember.contact})});$('#memberPaidMsg').innerHTML=`<div class="box">${state.lang==='zh'?'付款提交已记录，商家确认后会员资格生效。':'Payment submission recorded. Membership activates after merchant confirmation.'}</div>`}catch(x){$('#memberPaidMsg').innerHTML=`<div class="error">${x.message}</div>`}};
$('#bookingForm').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));try{const j=await req('/api/event-bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(o)});state.lastBooking={...j,...o};e.target.hidden=true;$('#bookingSuccess').hidden=false;$('#bookingNumber').textContent=j.booking_number;$('#bookingCheckout').innerHTML=`<div class="box"><strong>${j.event_title}</strong><p>$${Number(j.amount_due).toFixed(2)}</p></div>`+(Number(j.amount_due)>0?payment(j.payment,j.booking_number):`<div class="box">${state.lang==='zh'?'该活动无需额外付款，等待商家开放地址。':'No additional event fee. Wait for the organizer to unlock the venue.'}</div>`)}catch(x){$('#bookingError').innerHTML=`<div class="error">${x.message}</div>`}};
$('#eventPaid').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));try{await req('/api/event-payment-submitted',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...o,booking_number:state.lastBooking.booking_number,member_number:state.lastBooking.member_number,contact:state.lastBooking.contact})});$('#eventPaidMsg').innerHTML=`<div class="box">${state.lang==='zh'?'活动付款提交已记录，商家确认后开放地址。':'Event payment submission recorded. The venue unlocks after confirmation.'}</div>`}catch(x){$('#eventPaidMsg').innerHTML=`<div class="error">${x.message}</div>`}};
$$('[data-status-tab]').forEach(b=>b.onclick=()=>{$$('[data-status-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#memberStatusForm').hidden=b.dataset.statusTab!=='member';$('#eventStatusForm').hidden=b.dataset.statusTab!=='event';$('#statusResult').innerHTML=''});
$('#memberStatusForm').onsubmit=async e=>{e.preventDefault();try{const j=await req('/api/membership-status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});$('#statusResult').innerHTML=`<div class="box"><h3>${tr('statusLabels.'+j.status)}</h3><p>${j.member_number} · ${j.name_zh||j.name_en}</p><p>${j.expires_at?'Expires: '+new Date(j.expires_at).toLocaleDateString():''}</p>${['awaiting_payment','payment_pending'].includes(j.status)?payment(j.payment,j.member_number):''}</div>`}catch(x){$('#statusResult').innerHTML=`<div class="error">${x.message}</div>`}};
$('#eventStatusForm').onsubmit=async e=>{e.preventDefault();try{const j=await req('/api/event-booking-status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});$('#statusResult').innerHTML=`<div class="box"><h3>${tr('statusLabels.'+j.status)}</h3><p>${j.title_zh||j.title_en} · $${Number(j.amount_due).toFixed(2)}</p>${['awaiting_payment','payment_pending'].includes(j.status)?payment(j.payment,j.booking_number):''}${j.private_venue?`<div class="box"><strong>Venue</strong><p>${j.private_venue}</p></div>`:''}</div>`}catch(x){$('#statusResult').innerHTML=`<div class="error">${x.message}</div>`}};
load().catch(e=>document.body.insertAdjacentHTML('afterbegin',`<div class="error" style="padding:12px;text-align:center">${e.message}</div>`));
})();
